[package]
name = "sealvault_dev_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sealvault_core = { path = "../../core" , features = ["without_global_executor"]}

actix-web = "4.1.0"
actix-files = "0.6.1"
env_logger = "0.9.0"
ethers-core = { version = "0.17", features = ["legacy", "eip712"] }
dotenv = "0.15.0"
log = { version = "0.4.17", features = ["serde"] }
tokio = "1.20.1"
